[project]
name = "pvz"
version = "1.0"

dependencies = [
    "pygame>=2.0.0",
    "pillow>=11.1.0"
]


[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"pvz" = ["config.json", "assets/*", "levels/*.json"]