[project]
name = "pvz"
version = "1.0"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"pvz" = ["config.json", "assets/*", "levels/*.json"]